<a href="https://colab.research.google.com/github/rawatinder1/learning_tensorFlow/blob/main/00_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## In this noteBook , we are going to cover some of the most fundamental concepts of tensors using TensorFlow.

## Introduction to Tensors

In [ ]:
# import TensorFlow
import tensorflow as tf
print(tf.__version__);

2.19.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
import tensorflow as tf

# 🔢 1. Scalars (0D tensor)
scalar = tf.constant(7)
print("Scalar:")
print(scalar)
print("Shape:", scalar.shape, "Rank:", tf.rank(scalar).numpy())
print("-" * 40)

# 📏 2. Vector (1D tensor)
vector = tf.constant([1, 2, 3])
print("Vector:")
print(vector)
print("Shape:", vector.shape, "Rank:", tf.rank(vector).numpy())
print("-" * 40)

# 🧮 3. Matrix (2D tensor)
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6]])
print("Matrix:")
print(matrix)
print("Shape:", matrix.shape, "Rank:", tf.rank(matrix).numpy())
print("-" * 40)

# 📦 4. 3D Tensor
tensor3d = tf.constant([[[1, 2], [3, 4]],
                        [[5, 6], [7, 8]]])
print("3D Tensor:")
print(tensor3d)
print("Shape:", tensor3d.shape, "Rank:", tf.rank(tensor3d).numpy())
print("-" * 40)

# 📸 5. Example: image-like 4D tensor (batch, height, width, channels)
image_tensor = tf.random.uniform(shape=(4, 28, 28, 3))  # 4 RGB images, 28x28 each
print("4D Tensor (like images):")
print(image_tensor)
print("Shape:", image_tensor.shape, "Rank:", tf.rank(image_tensor).numpy())
print("-" * 40)

# 🧠 6. Tensor properties
print("Data type:", image_tensor.dtype)
print("Number of elements:", tf.size(image_tensor).numpy())

# 📚 Summary
print("""
✅ Tensors are:
- Multi-dimensional arrays (scalars, vectors, matrices, higher-D)
- Defined by rank (number of dimensions) and shape
- Backbone of deep learning data & model weights
- GPU/TPU-compatible and support automatic differentiation
""")


In [ ]:
# creating a multidimensional tensor;
tensor = tf.constant(7,shape=(3,2,3,3,2),
dtype=tf.float32)

print(tensor.ndim);
tensor

5


<tf.Tensor: shape=(3, 2, 3, 3, 2), dtype=float32, numpy=
array([[[[[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]]],


        [[[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]]]],



       [[[[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]]],


        [[[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]]]],



       [[[[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]]],



In [ ]:
tensor1=tf.constant([6,7])
tensor2=tf.constant([9,8])
result=tensor1*tensor2;
print(result)

tf.Tensor([54 56], shape=(2,), dtype=int32)


## creating tensors with `tf.variable()`

In [ ]:
# tf.variable is the mutable counterpart of tf.constant..
#  tf.Variable(
#     initial_value,
#     trainable=True,
#     dtype=None,
#     shape=None,
#     name=None
# )
# Key parameters:

# initial_value – The starting value (can be a number, list, NumPy array, or another tensor).

# trainable (default=True) – If True, TensorFlow will update it during training (e.g., by gradient descent).

# dtype – Data type (inferred if not given).

# shape – Shape of the variable (inferred if not given).

# name – Optional name.

mat = tf.Variable(tf.ones((2, 3)) * 7, dtype=tf.int32)
mat[1,2].assign(52)
mat


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 7.,  7.,  7.],
       [ 7.,  7., 52.]], dtype=float32)>

In [ ]:
import tensorflow as tf
changeable_tensor=tf.Variable(trainable=True,dtype=tf.float32,initial_value=tf.ones((2,3))*7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[7., 7., 7.],
       [7., 7., 7.]], dtype=float32)>

In [ ]:
g = tf.random.Generator.from_seed(42)

random_variable=g.truncated_normal(shape=(3,2),mean=5.0,stddev=1.0)
trainable_variable=tf.Variable(random_variable,trainable=True)
print(trainable_variable)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[4.2434196, 4.9314528],
       [5.07595  , 3.7426157],
       [5.7093353, 3.8071513]], dtype=float32)>


In [ ]:
## they are different ways you can create random tensors some of them are:->
# using uniform distribution this will randomly generate numbers using a unifrm distribution or rectagular distribution the probability of selecting any number between a range [a,b] is fixed.
random_tensor=tf.random.Generator.from_seed(42); # set seed for reproducibility.
trainable_tensor=random_tensor.uniform(shape=(3,2),minval=0,maxval=100,dtype=tf.int32) # generate only int data type values for tensor;
print(trainable_tensor);
# using normal distributio or gaussian where probability is maximum around mean and decays exponentially in every dimensions that moves away from that mean value.
trainable_tensor2=random_tensor.normal(shape=(3,2),mean=5.0,stddev=1.0)
print(trainable_tensor2);
# using trancated normal thats same as gaussian but outputs are truncated if theu are away from mean by +- 2*stddev.
trainable_tensor3=random_tensor.truncated_normal(shape=(3,2),mean=5.0,stddev=1.0)
print(trainable_tensor3);


tf.Tensor(
[[ 3 97]
 [26 98]
 [26 81]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[5.1752267 5.7110553]
 [5.5488243 5.14896  ]
 [4.45242   5.6163435]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[6.286623  4.285244 ]
 [4.898045  5.3831787]
 [5.3264775 5.17025  ]], shape=(3, 2), dtype=float32)
