<a href="https://colab.research.google.com/github/rawatinder1/learning_tensorFlow/blob/main/00_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## In this noteBook , we are going to cover some of the most fundamental concepts of tensors using TensorFlow.

## Introduction to Tensors

In [ ]:
# import TensorFlow
import tensorflow as tf
print(tf.__version__);

2.19.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
import tensorflow as tf

#  1. Scalars (0D tensor)
scalar = tf.constant(7)
print("Scalar:")
print(scalar)
print("Shape:", scalar.shape, "Rank:", tf.rank(scalar).numpy())
print("-" * 40)

#  2. Vector (1D tensor)
vector = tf.constant([1, 2, 3])
print("Vector:")
print(vector)
print("Shape:", vector.shape, "Rank:", tf.rank(vector).numpy())
print("-" * 40)

#  3. Matrix (2D tensor)
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6]])
print("Matrix:")
print(matrix)
print("Shape:", matrix.shape, "Rank:", tf.rank(matrix).numpy())
print("-" * 40)

#  4. 3D Tensor
tensor3d = tf.constant([[[1, 2], [3, 4]],
                        [[5, 6], [7, 8]]])
print("3D Tensor:")
print(tensor3d)
print("Shape:", tensor3d.shape, "Rank:", tf.rank(tensor3d).numpy())
print("-" * 40)

#  5. Example: image-like 4D tensor (batch, height, width, channels)
image_tensor = tf.random.uniform(shape=(4, 28, 28, 3))  # 4 RGB images, 28x28 each
print("4D Tensor (like images):")
print(image_tensor)
print("Shape:", image_tensor.shape, "Rank:", tf.rank(image_tensor).numpy())
print("-" * 40)

#  6. Tensor properties
print("Data type:", image_tensor.dtype)
print("Number of elements:", tf.size(image_tensor).numpy())

#  Summary
print("""
 Tensors are:
- Multi-dimensional arrays (scalars, vectors, matrices, higher-D)
- Defined by rank (number of dimensions) and shape
- Backbone of deep learning data & model weights
- GPU/TPU-compatible and support automatic differentiation
""")


In [ ]:
# creating a multidimensional tensor;
tensor = tf.constant(7,shape=(3,2,3,3,2),
dtype=tf.float32)

print(tensor.ndim);
tensor

5


<tf.Tensor: shape=(3, 2, 3, 3, 2), dtype=float32, numpy=
array([[[[[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]]],


        [[[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]]]],



       [[[[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]]],


        [[[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]]]],



       [[[[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]],

         [[7., 7.],
          [7., 7.],
          [7., 7.]]],



In [ ]:
tensor1=tf.constant([6,7])
tensor2=tf.constant([9,8])
result=tensor1*tensor2;
print(result)

tf.Tensor([54 56], shape=(2,), dtype=int32)


## creating tensors with `tf.variable()`

In [ ]:
# tf.variable is the mutable counterpart of tf.constant..
#  tf.Variable(
#     initial_value,
#     trainable=True,
#     dtype=None,
#     shape=None,
#     name=None
# )
# Key parameters:

# initial_value – The starting value (can be a number, list, NumPy array, or another tensor).

# trainable (default=True) – If True, TensorFlow will update it during training (e.g., by gradient descent).

# dtype – Data type (inferred if not given).

# shape – Shape of the variable (inferred if not given).

# name – Optional name.

mat = tf.Variable(tf.ones((2, 3)) * 7, dtype=tf.int32)
mat[1,2].assign(52)
mat


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 7.,  7.,  7.],
       [ 7.,  7., 52.]], dtype=float32)>

In [ ]:
import tensorflow as tf
changeable_tensor=tf.Variable(trainable=True,dtype=tf.float32,initial_value=tf.ones((2,3))*7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[7., 7., 7.],
       [7., 7., 7.]], dtype=float32)>

In [ ]:
g = tf.random.Generator.from_seed(42)

random_variable=g.truncated_normal(shape=(3,2),mean=5.0,stddev=1.0)
trainable_variable=tf.Variable(random_variable,trainable=True)
print(trainable_variable)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[4.2434196, 4.9314528],
       [5.07595  , 3.7426157],
       [5.7093353, 3.8071513]], dtype=float32)>


In [ ]:
## they are different ways you can create random tensors some of them are:->
# using uniform distribution this will randomly generate numbers using a unifrm distribution or rectagular distribution the probability of selecting any number between a range [a,b] is fixed.
random_tensor=tf.random.Generator.from_seed(42); # set seed for reproducibility.
trainable_tensor=random_tensor.uniform(shape=(3,2),minval=0,maxval=100,dtype=tf.int32) # generate only int data type values for tensor;
print(trainable_tensor);
# using normal distributio or gaussian where probability is maximum around mean and decays exponentially in every dimensions that moves away from that mean value.
trainable_tensor2=random_tensor.normal(shape=(3,2),mean=5.0,stddev=1.0)
print(trainable_tensor2);
# using trancated normal thats same as gaussian but outputs are truncated if theu are away from mean by +- 2*stddev.
trainable_tensor3=random_tensor.truncated_normal(shape=(3,2),mean=5.0,stddev=1.0)
print(trainable_tensor3);


tf.Tensor(
[[ 3 97]
 [26 98]
 [26 81]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[5.1752267 5.7110553]
 [5.5488243 5.14896  ]
 [4.45242   5.6163435]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[6.286623  4.285244 ]
 [4.898045  5.3831787]
 [5.3264775 5.17025  ]], shape=(3, 2), dtype=float32)


##shuffle order of elements in a tensor
> It looks like if you want the same order for your shuffled tensor you should set the global seed not the operation level seed


In [51]:
## shuffle a tensor(valuable for when you want to shuffle your data so that the inherent order doesnt effect learning )
# Shuffling the order of elements in a tensor is a valuable technique in machine learning for several reasons:

# Preventing bias: In machine learning, the order of data can sometimes influence the learning process, leading to biased models. Shuffling helps to break any inherent order or patterns in the data, ensuring that the model doesn't learn from the order itself.
# Improving generalization: By presenting data in a random order, shuffling helps the model to generalize better to unseen data. It prevents the model from memorizing the training data's order and encourages it to learn the underlying patterns.
# Ensuring independent and identically distributed (IID) data: Many machine learning algorithms assume that the data is IID. Shuffling helps to approximate this assumption by making the data points more independent of each other's position in the dataset.
# Better convergence: In some optimization algorithms used for training models, shuffling the data can lead to faster and more stable convergence.
# Essentially, shuffling helps to make the training process more robust and leads to better-performing models.

import tensorflow as tf
not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])
tf.random.set_seed(42); # global level seed
shuffled=tf.random.shuffle(not_shuffled ,seed=42) # operation level seed
print(shuffled)



tf.Tensor(
[[ 3  4]
 [ 2  5]
 [10  7]], shape=(3, 2), dtype=int32)


 ## Turning numpy arrays into tensors
 > NumPy arrays and TensorFlow tensors are fundamental data structures. While they can look similar and you can convert between them (as shown in your notebook), there are some key differences:

 > GPU/TPU Acceleration: TensorFlow tensors can be seamlessly moved to and run on GPUs (Graphics Processing Units) or TPUs (Tensor Processing Units) for significant speedups in numerical computations, especially for large-scale deep learning tasks. NumPy operations primarily run on the CPU.


 > Automatic Differentiation: TensorFlow tensors are designed to work with TensorFlow's automatic differentiation system. This is crucial for training neural networks, where gradients need to be calculated efficiently. NumPy does not have built-in automatic differentiation capabilities.


 > Immutability vs. Mutability: By default, tf.constant tensors are immutable (their values cannot be changed after creation), whereas tf.Variable tensors are mutable. NumPy arrays are generally mutable.


 > Distributed Computing: TensorFlow is built to handle distributed computing, allowing you to run computations across multiple machines or devices. NumPy is primarily for single-machine processing.


 > Use Case: While NumPy is a general-purpose library for numerical computing and is excellent for tasks like data analysis and scientific computing, TensorFlow tensors are specifically designed and optimized for building and running deep learning models.


 > In summary, while you can perform similar operations on both, TensorFlow tensors are specifically engineered for the demands of deep learning, offering acceleration, automatic differentiation, and scalability that are not inherent in NumPy arrays.



In [59]:
import numpy as np
import tensorflow as tf
array=np.arange(1,25,dtype=np.int32)
print(array);
# try experimenting with shapes make sure dimproduct doesnt exceed the total number of
# elements in the numpy array.
A=tf.constant(array,shape=(2,3,2,2))
print("Dimensions of tensor A : " , A.ndim)
print(A)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Dimensions of tensor A :  4
tf.Tensor(
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]]


 [[[13 14]
   [15 16]]

  [[17 18]
   [19 20]]

  [[21 22]
   [23 24]]]], shape=(2, 3, 2, 2), dtype=int32)


## Getting information from our Tensor

In [70]:
# * Shape -> the length (number of elements) of each of the dimension of a tensor.
# * Rank  -> the number of tensor dimensions.(tensor.ndim)
# * Axis or Dimension -> A particular dimenion of a tensor
# * Size -> The total number of items in the tensor
import tensorflow as tf;
def getInfo(tensor):
  print(tensor)
  print("size : ", tf.size(tensor).numpy())
  print("Rank : ", tensor.ndim)
  print("Shape : ", tensor.shape)
  print("axis 0 : ", tensor[0]);
  print("number of elements on 0th axis",tensor.shape[0])
  print("number of elements on last axis",tensor.shape[-1])

tensor=tf.constant([[1,2],
                    [5,7],
                    [5,9]]);
getInfo(tensor)

  # The shape (3, 2) tells us that the tensor has 2 dimensions.
  # The first number in the shape, 3, represents the number of elements along the 0th axis (often thought of as rows).
  # The second number in the shape, 2, represents the number of elements along the 1st axis (often thought of as columns).
  # So, for your tensor tf.constant([[1,2],[5,7],[5,9]]):

  # Along the 0th axis, you have three "groups" or "rows": [1, 2], [5, 7], and [5, 9]. That's why there are 3 elements on the 0th axis.
  # Along the 1st axis, within each of those groups, you have two elements: 1 and 2, 5 and 7, 5 and 9. That's why there are 2 elements on the 1st axis.
  # The output "number of elements on 0th axis 3" is correct based on the tensor's shape of (3, 2).

  # Does that explanation help clarify how the shape relates to the number of elements on each axis?




tf.Tensor(
[[1 2]
 [5 7]
 [5 9]], shape=(3, 2), dtype=int32)
size :  6
Rank :  2
Shape :  (3, 2)
axis 0 :  tf.Tensor([1 2], shape=(2,), dtype=int32)
number of elements on 0th axis 3
number of elements on last axis 2


## Indexing in Python Lists and TensorFlow Tensors

Both Python lists and TensorFlow tensors support indexing, which allows you to access individual elements or subsets of elements. While the syntax can be similar, it's important to understand the nuances of each.

**Python Lists:**

*   Lists are ordered collections of items.
*   Indexing is used to access elements based on their position (starting from 0).
*   You can use single indices, slicing (`[start:stop:step]`), and negative indices.

**TensorFlow Tensors:**

*   Tensors are multi-dimensional arrays.
*   Indexing is used to access elements or slices along each dimension.
*   Similar to NumPy arrays, you can use single indices, slicing, and advanced indexing techniques.
*   Key difference: When slicing tensors, the resulting tensor retains its rank unless you explicitly squeeze a dimension of size 1.

Let's look at some examples.

In [75]:
import tensorflow as tf

# Python List
my_list = [10, 20, 30, 40, 50]

# Accessing elements in a list
print("Python List Indexing:")
print("First element:", my_list[0])
print("Third element:", my_list[2])
print("Last element:", my_list[-1])
print("Slice from index 1 to 3:", my_list[1:4])
print("Every other element:", my_list[::2])

print("-" * 45)

# TensorFlow Tensor
my_tensor = tf.constant([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])

# Accessing elements in a tensor
print("TensorFlow Tensor Indexing:")
print("First row:", my_tensor[0])
print("Third row:", my_tensor[2])
print("Last row:", my_tensor[-1])
print("Element at row 1, column 2:", my_tensor[1, 2])
print("Slice of rows from 0 to 1:", my_tensor[0:2, :])
print("Slice of columns from 1 onwards:", my_tensor[:, 1:])
print("Element at row 0, column 0:", my_tensor[0, 0].numpy()) # Use .numpy() to get the scalar value

# Similarities:
# - Both use square brackets [] for indexing.
# - Both support slicing with start:stop:step.
# - Both support negative indexing to access elements from the end.

# Differences:
# - Tensors support multi-dimensional indexing (e.g., [row, column]).
# - Slicing a tensor generally retains the original number of dimensions (rank).

Python List Indexing:
First element: 10
Third element: 30
Last element: 50
Slice from index 1 to 3: [20, 30, 40]
Every other element: [10, 30, 50]
---------------------------------------------
TensorFlow Tensor Indexing:
First row: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Third row: tf.Tensor([7 8 9], shape=(3,), dtype=int32)
Last row: tf.Tensor([7 8 9], shape=(3,), dtype=int32)
Element at row 1, column 2: tf.Tensor(6, shape=(), dtype=int32)
Slice of rows from 0 to 1: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Slice of columns from 1 onwards: tf.Tensor(
[[2 3]
 [5 6]
 [8 9]], shape=(3, 2), dtype=int32)
Element at row 0, column 0: 1


## Indexing in tensors

In [78]:
my_list=[2,2,5,7,2,10,4,2,4]
print(my_list[:4]);

[2, 2, 5, 7]


## Expanding tensor and operations on tensors
> `+`,`-`,`*`,`\`





In [128]:
tensor_rank_4=tensor;
tensor_rank_5=tf.expand_dims(tensor_rank_4,axis=-1)
#tensor_rank_5=tensor[... , tf.newaxis]
#print(tensor_rank_5.shape)
print(tensor_rank_5)
print(tf.multiply(tensor,10))
print(tf.add(tensor,10000))


tf.Tensor(
[[[[[ 1]
    [ 2]]

   [[ 3]
    [ 4]]

   [[ 5]
    [ 6]]]


  [[[ 7]
    [ 8]]

   [[ 9]
    [10]]

   [[11]
    [12]]]]



 [[[[13]
    [14]]

   [[15]
    [16]]

   [[17]
    [18]]]


  [[[19]
    [20]]

   [[21]
    [22]]

   [[23]
    [24]]]]], shape=(2, 2, 3, 2, 1), dtype=int32)
tf.Tensor(
[[[[ 10  20]
   [ 30  40]
   [ 50  60]]

  [[ 70  80]
   [ 90 100]
   [110 120]]]


 [[[130 140]
   [150 160]
   [170 180]]

  [[190 200]
   [210 220]
   [230 240]]]], shape=(2, 2, 3, 2), dtype=int32)
tf.Tensor(
[[[[10001 10002]
   [10003 10004]
   [10005 10006]]

  [[10007 10008]
   [10009 10010]
   [10011 10012]]]


 [[[10013 10014]
   [10015 10016]
   [10017 10018]]

  [[10019 10020]
   [10021 10022]
   [10023 10024]]]], shape=(2, 2, 3, 2), dtype=int32)


## Broadcasting in TensorFlow

TensorFlow uses broadcasting to perform element-wise operations on tensors with different, but compatible, shapes. This allows operations like addition and division without requiring the tensors to have the exact same shape and size.

When shapes are compatible, TensorFlow "stretches" or "copies" the smaller tensor along dimensions to match the shape of the larger tensor, without actually duplicating the data.

**Broadcasting Rules (simplified):**

1.  Compare shapes from right to left.
2.  Dimensions are compatible if they are equal or one of them is 1.
3.  If a dimension is missing in one tensor, it's padded with a dimension of size 1 on the left.
4.  If dimensions are incompatible, an error occurs.

**Examples:**

*   Adding a scalar to a tensor:

In [134]:
import tensorflow as tf
tensor_A = tf.constant([[1], [2], [3]]) # Shape (3, 1)
tensor_B = tf.constant([[10, 20, 30]]) # Shape (1, 3)
result = tensor_A + tensor_B         # Result shape (3, 3)
print(result)

tf.Tensor(
[[11 21 31]
 [12 22 32]
 [13 23 33]], shape=(3, 3), dtype=int32)


In [177]:
import numpy as np
import tensorflow as tf
tensor_C=tf.constant(np.arange(1,13,dtype=np.int32),shape=(2,1,2,3));
tensor_D=tf.constant(np.arange(1,145,dtype=np.int32),shape=(3,2,4,3,2));

tensor_result=tf.matmul(tensor_C , tensor_D)
tensor_result

<tf.Tensor: shape=(3, 2, 4, 2, 2), dtype=int32, numpy=
array([[[[[  22,   28],
          [  49,   64]],

         [[  58,   64],
          [ 139,  154]],

         [[  94,  100],
          [ 229,  244]],

         [[ 130,  136],
          [ 319,  334]]],


        [[[ 652,  676],
          [ 895,  928]],

         [[ 796,  820],
          [1093, 1126]],

         [[ 940,  964],
          [1291, 1324]],

         [[1084, 1108],
          [1489, 1522]]]],



       [[[[ 310,  316],
          [ 769,  784]],

         [[ 346,  352],
          [ 859,  874]],

         [[ 382,  388],
          [ 949,  964]],

         [[ 418,  424],
          [1039, 1054]]],


        [[[1804, 1828],
          [2479, 2512]],

         [[1948, 1972],
          [2677, 2710]],

         [[2092, 2116],
          [2875, 2908]],

         [[2236, 2260],
          [3073, 3106]]]],



       [[[[ 598,  604],
          [1489, 1504]],

         [[ 634,  640],
          [1579, 1594]],

         [[ 670,  676],
         

## Broadcasting with `tf.matmul`

When using `tf.matmul` to perform matrix multiplication on tensors, TensorFlow supports broadcasting not only on the last two dimensions (the matrices being multiplied) but also on the dimensions *before* the last two. These preceding dimensions are often referred to as "batch" dimensions.

This means you can perform matrix multiplication between tensors of different ranks, provided their shapes are compatible according to broadcasting rules for these batch dimensions, and the inner dimensions of the last two dimensions match for the matrix multiplication itself.

**How `tf.matmul` Broadcasting Works:**

1.  **Matrix Dimensions:** The last two dimensions of the tensors are treated as the matrices. For the operation to be valid, the inner dimensions of these matrices must match (the number of columns in the first matrix must equal the number of rows in the second matrix).
2.  **Batch Dimensions:** The dimensions before the last two are considered batch dimensions. TensorFlow applies standard broadcasting rules to these batch dimensions from left to right.
3.  **Result Shape:** The shape of the resulting tensor will have the broadcasted batch dimensions followed by the outer dimensions of the matrix multiplication result.

**Example:**

Consider `tensor_C` with shape `(2, 2, 2, 3)` (Rank 4) and `tensor_D` with shape `(1, 2, 1, 3, 2)` (Rank 5).

*   **Matrix Dimensions:** `(2, 3)` from `tensor_C` and `(3, 2)` from `tensor_D`. The inner dimensions (3 and 3) match. The result of the matrix multiplication on these dimensions will have shape `(2, 2)`.
*   **Batch Dimensions:** `(2, 2)` from `tensor_C` and `(1, 2, 1)` from `tensor_D`. Applying broadcasting rules:
    *   Dimension 0: `2` vs `1` -> Broadcasts to `2`
    *   Dimension 1: `2` vs `2` -> Compatible, result is `2`
    *   Dimension 2 (from tensor_D only): `1` -> Broadcasts to `1`
    *   The broadcasted batch shape is effectively `(2, 2, 1)`. This, combined with the matrix multiplication result shape `(2, 2)`, gives a final shape of `(2, 2, 1, 2, 2)`. The output shape `(1, 2, 2, 2, 2)` seen previously is likely due to the initial dimension of 1 in `tensor_D` influencing the broadcasted batch shape.

The final result shape combines the broadcasted batch dimensions and the matrix multiplication result shape.

This broadcasting capability in `tf.matmul` is powerful as it allows for efficient operations across batches of matrices without explicit loops.
👇

🧠 Note on tf.matmul broadcasting rules:

✅ Inner dimensions must match exactly:
The last dimension of A and the second-to-last of B must be equal.

If A is (..., m, n) and B is (..., n, p) → result is (..., m, p)

✅ Leading (batch) dimensions can broadcast, but only if they are either equal or 1.

Example: (1, m, n) × (b, n, p) → (b, m, p) ✅

Example: (b, m, n) × (b, n, p) → (b, m, p) ✅

❌ If any leading dimension is different and neither is 1, broadcasting fails.

Example: (b, m, n) × (c, n, p) → ❌ fails if b ≠ c and neither is 1.

✅ If B has no batch dimension (e.g., shape (n, p)), it is treated as shared across all batches.

Example: (b, m, n) × (n, p) → (b, m, p)



🧠 Note – Why tf.matmul Worked With (2,2,2,3) × (3,2,1,3,2)

Even though the shapes of the two tensors look incompatible, tf.matmul did not break its rules. Here’s why the operation succeeds:

Inner dimensions must match

Last two dims of tensor_C: (2, 3)

Last two dims of tensor_D: (3, 2)
✅ 3 == 3 → inner matmul is valid → (2, 3) × (3, 2) → (2, 2)

Batch dimensions can broadcast

tensor_C batch dims: (2, 2)

tensor_D batch dims: (3, 2, 1)

Aligning from right:

2 vs 1 → ✅ 1 broadcasts to 2

2 vs 2 → ✅ equal

(missing) vs 3 → ✅ missing dims treated as 1, then broadcast to 3

✅ Resulting batch shape: (3, 2, 2)

Final result shape
Combine broadcasted batch dims (3, 2, 2) with the matmul result (2, 2)
→ Final tensor shape: (3, 2, 2, 2, 2)

💡 Key Takeaways:

TensorFlow treats missing batch dimensions as 1, allowing broadcasting.

A 1 in any batch dimension makes a tensor more flexible — it can “expand” to match larger shapes.

The matmul rule ((..., m, n) × (..., n, p) → (..., m, p)) is always respected — this example just shows broadcasting at work.